import { useEffect, useMemo, useState } from "react";
import { Link } from "react-router-dom";
import { ExternalLink, Heart, Search, SlidersHorizontal } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import Navbar from "@/components/Navbar";
import PublicFooter from "@/components/PublicFooter";
import Seo from "@/components/Seo";
import LiveDataBadge from "@/components/LiveDataBadge";
import TrendBadge from "@/components/TrendBadge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar";
import { useAuth } from "@/hooks/useAuth";
import { approvalRate, avgPayoutDays, formatDays, groupByFirm, trendDelta } from "@/lib/stats";
import { formatDistanceToNow } from "date-fns";

const Firms = () => {
  const { user } = useAuth();
  const [firms, setFirms] = useState<any[]>([]); const [cases, setCases] = useState<any[]>([]);
  const [query, setQuery] = useState(""); const [sort, setSort] = useState("verified"); const [followed, setFollowed] = useState<string[]>([]); const [onlyFollowing, setOnlyFollowing] = useState(false);
  const load = async () => { const [{ data: firmData }, { data: caseData }] = await Promise.all([supabase.from("firms").select("*"), supabase.from("payout_cases").select("firm_id, status, amount, created_at, payout_date, verification_status")]); setFirms(firmData || []); setCases(caseData || []); };
  useEffect(() => { load(); const channel = supabase.channel("firm-directory-live").on("postgres_changes", { event: "*", schema: "public", table: "payout_cases" }, load).on("postgres_changes", { event: "*", schema: "public", table: "firms" }, load).subscribe(); return () => { supabase.removeChannel(channel); }; }, []);
  useEffect(() => { if (!user) { setFollowed([]); return; } supabase.from("firm_follows").select("firm_id").eq("user_id", user.id).then(({ data }) => setFollowed((data || []).map((item) => item.firm_id))); }, [user]);
  const grouped = useMemo(() => groupByFirm(cases), [cases]);
  const visible = useMemo(() => firms.map((firm) => { const list = grouped[firm.id] || []; const verifiedApprovals = list.filter((item) => item.status === "approved" && ["verified", "community_confirmed"].includes(item.verification_status)); const reportedDenials = list.filter((item) => item.status === "denied"); return { firm, list, verifiedApprovals, reportedDenials, rate: approvalRate(list), avg: avgPayoutDays(list), trend: trendDelta(list), latest: verifiedApprovals.sort((a, b) => new Date(b.created_at).getTime() - new Date(a.created_at).getTime())[0] }; }).filter((item) => item.verifiedApprovals.length > 0 && item.firm.name.toLowerCase().includes(query.toLowerCase()) && (!onlyFollowing || followed.includes(item.firm.id))).sort((a, b) => sort === "ratio" ? b.rate - a.rate : sort === "fastest" ? (a.avg ?? Infinity) - (b.avg ?? Infinity) : sort === "activity" ? b.list.length - a.list.length : b.verifiedApprovals.length - a.verifiedApprovals.length), [firms, grouped, query, onlyFollowing, followed, sort]);

  return <div className="min-h-screen bg-background"><Seo title="Explore Prop Firms | Payout Cases" description="Explore firms with verified payout activity tracked by Payout Cases." path="/firms" /><Navbar />
    <header className="bg-obsidian text-ivory"><div className="container mx-auto px-4 pb-16 pt-32"><LiveDataBadge /><h1 className="mt-5 text-5xl font-extrabold md:text-7xl">Explore Prop Firms</h1><p className="mt-5 max-w-2xl text-lg text-ivory-muted">Explore firms with verified payout activity tracked by Payout Cases.</p></div></header>
    <main className="container mx-auto px-4 py-12"><div className="mb-10 grid gap-3 border-y border-border py-4 md:grid-cols-[1fr_220px_auto]"><div className="relative"><Search className="absolute left-3 top-3 h-4 w-4 text-muted-foreground" /><Input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search eligible firms" className="pl-9" /></div><Select value={sort} onValueChange={setSort}><SelectTrigger><SlidersHorizontal className="mr-2 h-4 w-4" /><SelectValue /></SelectTrigger><SelectContent><SelectItem value="verified">Most verified payouts</SelectItem><SelectItem value="ratio">Best approval ratio</SelectItem><SelectItem value="activity">Most activity</SelectItem><SelectItem value="fastest">Fastest payout</SelectItem></SelectContent></Select><Button variant={onlyFollowing ? "default" : "outline"} disabled={!user} onClick={() => setOnlyFollowing((value) => !value)}><Heart className={onlyFollowing ? "fill-current" : ""} /> Following</Button></div>
      <div className="mb-7 flex items-center justify-between"><p className="font-mono text-xs uppercase text-muted-foreground">{visible.length} publicly eligible firms</p><p className="text-xs text-muted-foreground">Eligibility requires a verified approval</p></div>
      <div className="grid gap-px bg-border lg:grid-cols-2">{visible.map(({ firm, list, verifiedApprovals, reportedDenials, rate, avg, trend, latest }) => <article key={firm.id} className="group bg-card p-7 transition-all hover:relative hover:z-10 hover:-translate-y-0.5 hover:shadow-premium"><div className="flex items-start justify-between gap-5"><div className="flex min-w-0 gap-4"><Avatar className="h-14 w-14 rounded-sm border border-border bg-secondary"><AvatarImage src={firm.logo_url || undefined} className="object-contain transition-transform group-hover:scale-105" /><AvatarFallback className="rounded-sm font-bold">{firm.name.slice(0, 2).toUpperCase()}</AvatarFallback></Avatar><div><h2 className="text-xl font-bold">{firm.name}</h2>{firm.website && <a href={firm.website} target="_blank" rel="noreferrer" className="mt-1 inline-flex items-center gap-1 text-xs text-muted-foreground hover:text-primary">Official website <ExternalLink className="h-3 w-3" /></a>}</div></div><TrendBadge delta={trend} /></div>
        <div className="mt-8 grid grid-cols-2 gap-6"><div><p className="data-label">Verified payouts</p><p className="mt-2 font-mono text-2xl font-semibold text-success">{verifiedApprovals.length}</p></div><div><p className="data-label">Reported denials</p><p className="mt-2 font-mono text-2xl font-semibold text-destructive">{reportedDenials.length}</p></div></div>
        <div className="mt-8"><div className="flex items-end justify-between"><div><p className="font-mono text-4xl font-semibold">{rate.toFixed(1)}%</p><p className="data-label mt-2">Approval ratio</p></div><p className="font-mono text-xs text-muted-foreground">Avg {formatDays(avg)}</p></div><div className="mt-4 h-1 bg-secondary"><div className="h-full bg-success transition-all duration-700" style={{ width: `${rate}%` }} /></div></div>
        <div className="mt-8 flex items-end justify-between border-t border-border pt-5"><div><p className="data-label">Last verified payout</p><p className="mt-1 text-sm">{latest ? formatDistanceToNow(new Date(latest.created_at), { addSuffix: true }) : "—"}</p></div><Button asChild variant="link" className="px-0"><Link to={`/firms/${firm.id}`}>View firm <span className="transition-transform group-hover:translate-x-1">→</span></Link></Button></div>
      </article>)}</div>{!visible.length && <div className="py-24 text-center"><p className="text-lg font-semibold">No eligible firms match this view</p><p className="mt-2 text-sm text-muted-foreground">A firm appears after its first verified payout approval.</p></div>}</main><PublicFooter /></div>;
};

export default Firms;