import { useEffect, useMemo, useState } from "react";
import { Link } from "react-router-dom";
import { motion, useMotionValue, useSpring } from "framer-motion";
import { ArrowRight, CheckCircle2, Database, FileCheck2, ShieldCheck, XCircle } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import Navbar from "@/components/Navbar";
import PublicFooter from "@/components/PublicFooter";
import Seo from "@/components/Seo";
import AnimatedCounter from "@/components/AnimatedCounter";
import SubmitCaseButton from "@/components/SubmitCaseButton";
import LiveDataBadge from "@/components/LiveDataBadge";
import CaseStatusBadge from "@/components/CaseStatusBadge";
import { Button } from "@/components/ui/button";
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar";
import { approvalRate, groupByFirm, trendDelta } from "@/lib/stats";
import TrendBadge from "@/components/TrendBadge";
import { formatDistanceToNow } from "date-fns";

const Index = () => {
  const [cases, setCases] = useState<any[]>([]);
  const [firms, setFirms] = useState<any[]>([]);
  const [notice, setNotice] = useState(false);
  const pointerX = useMotionValue(0); const pointerY = useMotionValue(0);
  const x = useSpring(pointerX, { stiffness: 45, damping: 22 }); const y = useSpring(pointerY, { stiffness: 45, damping: 22 });
  const load = async () => { const [{ data: caseData }, { data: firmData }] = await Promise.all([supabase.from("payout_cases").select("*, firms(name, logo_url) ").order("created_at", { ascending: false }), supabase.from("firms").select("*")]); setCases(caseData || []); setFirms(firmData || []); };
  useEffect(() => { load(); const channel = supabase.channel("home-intelligence").on("postgres_changes", { event: "*", schema: "public", table: "payout_cases" }, () => { load(); setNotice(true); window.setTimeout(() => setNotice(false), 3500); }).subscribe(); return () => { supabase.removeChannel(channel); }; }, []);
  const verified = cases.filter((item) => ["verified", "community_confirmed"].includes(item.verification_status));
  const verifiedApprovals = verified.filter((item) => item.status === "approved");
  const denials = cases.filter((item) => item.status === "denied");
  const volume = verifiedApprovals.reduce((sum, item) => sum + Number(item.amount || 0), 0);
  const eligibleFirmIds = new Set(verifiedApprovals.map((item) => item.firm_id));
  const topFirms = useMemo(() => Object.entries(groupByFirm(cases)).map(([id, list]) => ({ firm: firms.find((item) => item.id === id), list, rate: approvalRate(list), trend: trendDelta(list), verified: list.filter((item) => item.status === "approved" && ["verified", "community_confirmed"].includes(item.verification_status)).length })).filter((item) => item.firm && item.verified > 0).sort((a, b) => b.verified - a.verified || b.rate - a.rate).slice(0, 3), [cases, firms]);

  return <div className="min-h-screen bg-background"><Seo title="Payout Cases — Verified Prop Firm Payout Intelligence" description="Explore verified payout approvals, denials and proof from proprietary trading firms." path="/" /><Navbar />
    <section className="financial-grid relative min-h-[92vh] overflow-hidden bg-obsidian text-ivory" onMouseMove={(event) => { pointerX.set((event.clientX / window.innerWidth - .5) * 10); pointerY.set((event.clientY / window.innerHeight - .5) * 10); }}>
      <div className="container mx-auto grid min-h-[92vh] items-center gap-12 px-4 pb-16 pt-28 lg:grid-cols-[.92fr_1.08fr]">
        <motion.div initial={{ opacity: 0, y: 18 }} animate={{ opacity: 1, y: 0 }} className="relative z-10"><LiveDataBadge /><h1 className="mt-7 max-w-3xl text-5xl font-extrabold leading-[1.02] md:text-7xl xl:text-[5.3rem]">Real Payout Data.<br /><span className="text-ivory-muted">Real Trading Experiences.</span></h1><p className="mt-7 max-w-xl text-lg leading-relaxed text-ivory-muted">Explore verified payout approvals, denials and proof from proprietary trading firms.</p><div className="mt-9 flex flex-wrap gap-3"><Button asChild size="lg" className="bg-ivory text-obsidian hover:bg-success hover:text-success-foreground"><Link to="/proofs">Explore payout proofs <ArrowRight /></Link></Button><SubmitCaseButton size="lg" variant="outline" className="border-ivory/30 text-ivory hover:border-ivory hover:text-ivory">Submit a case</SubmitCaseButton></div><div className="mt-12 flex items-center gap-6 border-t border-ivory/10 pt-5 text-xs text-ivory-muted"><span className="flex items-center gap-2"><ShieldCheck className="h-4 w-4 text-success" /> Verification states</span><span className="flex items-center gap-2"><Database className="h-4 w-4 text-success" /> Live records</span></div></motion.div>
        <motion.div style={{ x, y }} className="relative z-10 lg:pl-8"><div className="border border-ivory/15 bg-obsidian-muted/95 shadow-2xl"><div className="flex items-center justify-between border-b border-ivory/10 px-5 py-4"><div><p className="data-label text-ivory-muted">Payout intelligence</p><p className="mt-1 text-sm font-semibold">Live activity terminal</p></div><LiveDataBadge label="SYNCED" /></div><div className="divide-y divide-ivory/10">{cases.slice(0, 5).map((item, index) => <motion.div key={item.id} initial={{ opacity: 0, x: 10 }} animate={{ opacity: 1, x: 0 }} transition={{ delay: .2 + index * .08 }} className="grid grid-cols-[1fr_auto] gap-4 px-5 py-5 sm:grid-cols-[1.1fr_.8fr_auto]"><div className="flex items-center gap-3"><Avatar className="h-8 w-8 rounded-sm border border-ivory/10"><AvatarImage src={item.firms?.logo_url || undefined} className="object-contain" /><AvatarFallback className="rounded-sm bg-ivory/10 text-[10px] text-ivory">{item.firms?.name?.slice(0, 2).toUpperCase()}</AvatarFallback></Avatar><div><p className="text-sm font-semibold">{item.firms?.name || "Unknown firm"}</p><p className="mt-1 font-mono text-[10px] text-ivory-muted">{formatDistanceToNow(new Date(item.created_at), { addSuffix: true })}</p></div></div><p className={`hidden self-center font-mono text-lg font-semibold sm:block ${item.status === "approved" ? "text-success" : "text-destructive-glow"}`}>{item.status === "approved" ? "+" : "−"}${Number(item.amount || 0).toLocaleString()}</p><div className="self-center"><CaseStatusBadge status={item.verification_status} /></div></motion.div>)}{!cases.length && <p className="px-5 py-20 text-center text-sm text-ivory-muted">Live records will appear here.</p>}</div><div className="flex justify-between border-t border-ivory/10 px-5 py-4 font-mono text-[10px] uppercase text-ivory-muted"><span>Updated continuously</span><span>{cases.length} total records</span></div></div></motion.div>
      </div>{notice && <motion.div initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} className="fixed bottom-5 right-5 z-50 border border-success/30 bg-obsidian px-4 py-3 text-sm text-ivory shadow-premium"><span className="mr-2 text-success">●</span>New payout record added</motion.div>}
    </section>

    <section className="overflow-hidden border-y border-border bg-card"><div className="flex min-w-max animate-[ticker_30s_linear_infinite] gap-12 px-4 py-3 font-mono text-xs uppercase text-muted-foreground">{[...cases.slice(0, 8), ...cases.slice(0, 8)].map((item, index) => <span key={`${item.id}-${index}`} className={item.status === "approved" ? "text-success" : "text-destructive"}>{item.status === "approved" ? "+" : "−"}${Number(item.amount || 0).toLocaleString()} {item.status} · {item.firms?.name}</span>)}</div></section>
    <section id="statistics" className="scroll-mt-20 bg-background py-20"><div className="container mx-auto px-4"><p className="section-kicker">Market overview</p><div className="grid border-y border-border md:grid-cols-4">{[{ label: "Verified approvals", value: verifiedApprovals.length, icon: CheckCircle2, tone: "text-success" }, { label: "Reported denials", value: denials.length, icon: XCircle, tone: "text-destructive" }, { label: "Prop firms tracked", value: eligibleFirmIds.size, icon: Database, tone: "text-foreground" }, { label: "Verified payout volume", value: volume, prefix: "$", icon: FileCheck2, tone: "text-success" }].map((stat) => <div key={stat.label} className="border-b border-border px-6 py-10 last:border-b-0 md:border-b-0 md:border-r md:last:border-r-0"><stat.icon className={`mb-8 h-5 w-5 ${stat.tone}`} /><p className={`font-mono text-4xl font-semibold md:text-5xl ${stat.tone}`}><AnimatedCounter end={stat.value} prefix={stat.prefix} /></p><p className="mt-3 text-sm text-muted-foreground">{stat.label}</p></div>)}</div></div></section>
    <section className="bg-obsidian py-20 text-ivory"><div className="container mx-auto px-4"><div className="mb-10 flex flex-wrap items-end justify-between gap-5"><div><p className="section-kicker text-success">Firm intelligence</p><h2 className="text-4xl font-extrabold md:text-5xl">Leading verified firms</h2></div><Button asChild variant="outline" className="border-ivory/20 text-ivory"><Link to="/firms">Explore all firms <ArrowRight /></Link></Button></div><div className="grid gap-px bg-ivory/10 lg:grid-cols-3">{topFirms.map(({ firm, list, rate, trend }) => <Link key={firm.id} to={`/firms/${firm.id}`} className="group bg-obsidian-muted p-7 transition-colors hover:bg-card hover:text-foreground"><div className="flex items-center justify-between"><Avatar className="h-14 w-14 rounded-sm border border-current/10"><AvatarImage src={firm.logo_url || undefined} className="object-contain" /><AvatarFallback className="rounded-sm">{firm.name.slice(0, 2).toUpperCase()}</AvatarFallback></Avatar><TrendBadge delta={trend} /></div><h3 className="mt-10 text-2xl font-bold">{firm.name}</h3><div className="mt-8 flex items-end justify-between"><div><p className="font-mono text-4xl font-semibold text-success">{rate.toFixed(1)}%</p><p className="data-label mt-2">Approval ratio</p></div><span className="transition-transform group-hover:translate-x-1">View firm →</span></div><div className="mt-6 h-1 bg-current/10"><div className="h-full bg-success" style={{ width: `${rate}%` }} /></div><p className="mt-5 font-mono text-xs text-current/60">{list.length} tracked cases</p></Link>)}</div>{!topFirms.length && <p className="border border-ivory/10 py-16 text-center text-ivory-muted">Firm rankings appear after verified approvals are recorded.</p>}</div></section>
    <section className="bg-background py-24"><div className="container mx-auto grid gap-14 px-4 lg:grid-cols-[.8fr_1.2fr]"><div><p className="section-kicker">Trust through evidence</p><h2 className="text-4xl font-extrabold md:text-5xl">Every claim carries its verification state.</h2><p className="mt-6 max-w-lg text-lg leading-relaxed text-muted-foreground">Payout Cases separates platform-verified evidence, community-confirmed records, reported submissions, and disputed claims so traders can judge each record clearly.</p></div><div className="divide-y divide-border border-y border-border">{[{ title: "Verified", body: "Evidence accepted under current platform verification rules.", tone: "text-success" }, { title: "Reported", body: "Submitted information awaiting stronger verification.", tone: "text-warning" }, { title: "Disputed", body: "A record flagged by the community for closer review.", tone: "text-destructive" }].map((item, i) => <motion.div key={item.title} initial={{ opacity: 0, y: 10 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} className="grid grid-cols-[48px_1fr] gap-5 py-7"><span className="font-mono text-sm text-muted-foreground">0{i + 1}</span><div><h3 className={`text-xl font-bold ${item.tone}`}>{item.title}</h3><p className="mt-2 text-sm leading-relaxed text-muted-foreground">{item.body}</p></div></motion.div>)}</div></div></section>
    <PublicFooter />
  </div>;
};

export default Index;